# Generated by Django 3.2.9 on 2021-11-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmarkpost',
            unique_together={('user', 'post')},
        ),
    ]
