# Generated by Django 3.2.9 on 2021-11-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211117_1651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user', 'user_following')},
        ),
    ]
