version: "3.9"

networks:
  blog_network:
    driver: bridge

services:
  db:
    image: postgres:13
    volumes:
      - ./api/data/db:/var/lib/postgresql/data
    networks:
      - blog_network
    ports:
      - 5432:5432
    env_file:
      - ./conf/db.env
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: ynot99/blog_django
    volumes:
      - ./api/images/avatars:/opt/blog/images/avatars
    networks:
      - blog_network
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./conf/api.env
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: ynot99/blog_react
    networks:
      - blog_network
    ports:
      - 3000:81
    depends_on:
      - api
  nginx:
    image: nginx:1.23.4
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - blog_network
    depends_on:
      - api
      - client
