version: "3.9"

networks:
  blog_network:
    driver: bridge

services:
  db:
    image: postgres:13
    volumes:
      - ./api/data/db:/var/lib/postgresql/data
    networks:
      - blog_network
    ports:
      - 5432:5432
    env_file:
      - ./conf/db.env
